language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: iBULl4ow3DPBZgqRXw82vatq5XGecdB+xWNr+bM/qlrgWgW9Fc3RTuZBj1g2E00G5QQpiWo9tA1xzYaG1QzpXVXcZMA1XZ5zSi3tfD18P3vM67hCCob55+/dIRVfz3Twyc8063NCozOpu6xbdB/jVRJKHeDCjLubOP4TuZeXsOrM/x6n9e8jfXNlKcbt2aTgU06Jbd4nhvPY8OQYrvp3uQ5HEOfkgldLYn9kRA9/S2aLosQEQ2CsZwoUyBZLrmVizQlUq6n/3Pu3swrJ0jJ2fa+HuY40XiRwmOPWdnzFUqryFdjYVkuGnmSXOp/0qS2BphxikUkeXWwE2cHmC38zfA210CrmFOa0bzoKwkF+CK7u6U7aSmtzq73UvtECE6/VCQCWFlLwAzubY6vb5n67IhjDXec8C+pgxT/EhljBHsO/LhfGvTBfCKtlIppCG6oElkujKws8p1CftkoLxSzC8zHO6WFTuj2g6SS01sqQVo3Y0Im0XBNe2BCxU6cOjqFvd4+86M1CYTRSq3oHwiEMu+qwzFzp81b6K8DAKc6yuIHx498j9A9J+tMTOIrXDf7wksceWxbgcRiCmIL+9vBBz5DxNV5T4iqVjsxg5M9AfezBu0+8xsXnD85qHeChs+D/I9uPtap5mvIxiw/DxcwPgBY5KMGD0ZI4LW50tbL8X6w=
  app: fathomless-sierra-38426
  on:
    repo: Laurn17/node-restaurants-app-mongoose
    branch: feature/with-tests
