language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: YLL5mA0fMZEkxKOVWrG3/iPkVIAtjiGti+V93xOAYYgwq/Givw+MEcN0g/TtD/BTqDaJzd223tjkmlONIel+xYy6QCn1a7N2V539JkChYiD66UjUViHcBLLANg7EdT57Pv/yG+U9ITeUQsZ+UwRxC23oGds9cu/VJGI9+eC0VxkK8v6XRd6n3mn2cqVsz521Ix6IN55A6lvtbfyo6ek4729dfjnUgRnYb/EA9NJyweyZyWBcEDpu1qW1eVRsaiEX+NQJTSfJirjlfvVM/onbc6YYN/t7nH3uKqWZfCOM1jr4RepRZuMtuTBcu7weUaQfi0LTmjEvmx9FYbNe0u91WwH7u4QOHPaTunsru2fO7htqU+4s52DA/XGqDLJDIp70zqc+UslM9xJYfRbWpRsTjOQaODkQyQF1LlzAmebmDOX+xq0OaR/+R3L6d9qsPidhbKjIIolQs1hdRD2Y60blO+zdthKiWMCBXcawQT1o0a02QcDVqnbvcSyCer/ppyOA7F315eNcMYPeCLsFNHWs9p39425EpGrGjiErRs2P2cbBz+Y1kgrqfOcdJ39CKPwua5nxV2Z2iPbyVEdQDKvsq+5GRfgDV+tOMT10ze83figa3JebgBnoi8fxOa5dhdijCydpoS51bq5VMQ06yDqW0rUhQlupbaOzj7wXg/jBAyM=
  app: enigmatic-ravine-14748
  on:
    repo: Laurn17/node-restaurants-app-mongoose
    branch: feature/with-tests

